version: '3.8'

services:
  my-blogpost-be:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./db.sqlite:/app/db.sqlite
      - ./migrations:/app/migrations
      - /etc/ssl/certs:/etc/ssl/certs
    ports:
      - "3000:3000"

  my-blogpost-fe:
    build:
      context: ./frontend/my-blogpost-fe
      dockerfile: Dockerfile
    container_name: my-blogpost-fe
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - my-blogpost-be